spring.application.name=tarefasrh

spring.config.import=optional:file:src/main/resources/application-local.properties

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tarefasrh_prototipo?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

google.sheets.id=${GOOGLE_SHEETS_ID:}
google.credentials.path=${GOOGLE_CREDENTIALS_PATH:secrets/google-credentials.json}
